import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Link from 'next/link';
// import { CiDark } from 'react-icons/ci';
import 'react-notion/src/styles.css';
import 'prismjs/themes/prism-tomorrow.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const navigationData = [
  {
    path: '/posts',
    pathName: 'POST',
  },
  {
    path: '/about',
    pathName: 'ABOUT',
  },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ko'>
      <body className={`${inter.className} `}>
        <header className='container mx-auto py-6 flex items-center'>
          <Link href={'/'} className='text-4xl font-semi-bold'>
            HEEJI
          </Link>

          <nav className='flex grow w-full'>
            <ul className='flex flex-row gap-4 w-full justify-end'>
              {navigationData.map((data) => (
                <li key={data.path}>
                  <Link href={data.path} className='text-lg'>
                    {data.pathName}
                  </Link>
                </li>
              ))}
            </ul>
          </nav>

          {/* <CiDark size={48} /> */}
        </header>

        <section className='max-w-screen-md mx-auto'>{children}</section>
      </body>
    </html>
  );
}
